

CREATE TABLE SNAPSHOTS (
	ID INT GENERATED ALWAYS AS IDENTITY CONSTRAINT ID_PK PRIMARY KEY,
	STIMESTAMP TIMESTAMP NOT NULL
);

CREATE TABLE TICKETS (
	SID INT,
	TICKETID INT,
	OWNER VARCHAR(50) NOT NULL,
	STATUS VARCHAR(50) NOT NULL,
	CONSTRAINT TICKETS_PK PRIMARY KEY (SID, TICKETID),
	CONSTRAINT TICKETS_FK FOREIGN KEY (SID) REFERENCES SNAPSHOTS (ID)
);

CREATE TABLE OWNERDATA (
	SID INT,
	NAME VARCHAR(50) NOT NULL,
	NUMOPEN INT,
	NUMCLOSED INT,
	NUMDEFERRED INT,
	NUMREASSIGNEDFROM INT,
	NUMNEW INT,
	NUMREOPENED INT,
	NUMREASSIGNEDTO INT,
	CONSTRAINT OWNERDATA_PK PRIMARY KEY (SID, NAME),
	CONSTRAINT OWNERDATA_FK FOREIGN KEY (SID) REFERENCES SNAPSHOTS (ID)
);
